version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - "1433:1433"

networks:
  app-network:
    driver: bridge
